part of store;

void _seedStore(InMemoryStore store) {
  final now = DateTime.now().toUtc();

  final admin = <String, dynamic>{
    'id': store._userId++,
    'name': 'Admin',
    'email': 'admin@ekusheycoding.com',
    'role': 'admin',
    'password_hash': store.hashPassword('admin123'),
    'api_token_hash': null,
    'username': 'admin',
    'phone': null,
    'bio': 'Platform administrator',
    'avatar': null,
    'github_url': null,
    'linkedin_url': null,
    'twitter_url': null,
    'portfolio_url': null,
    'location': 'Dhaka, Bangladesh',
    'timezone': 'Asia/Dhaka',
    'date_of_birth': null,
    'skill_level': 'expert',
    'programming_languages': <String>['JavaScript', 'PHP', 'Dart'],
    'interests': <String>['Web Development', 'Platform Management'],
    'badges': <String>['admin'],
    'daily_goal_minutes': 60,
    'email_notifications': true,
    'is_public': true,
    'current_streak': 14,
    'longest_streak': 30,
    'created_at': now.subtract(const Duration(days: 120)).toIso8601String(),
    'updated_at': now.toIso8601String(),
    'email_verified_at': now.toIso8601String(),
  };

  final testUser = <String, dynamic>{
    'id': store._userId++,
    'name': 'Test User',
    'email': 'test@example.com',
    'role': 'user',
    'password_hash': store.hashPassword('password123'),
    'api_token_hash': null,
    'username': 'testuser',
    'phone': null,
    'bio': 'Learning full stack development.',
    'avatar': null,
    'github_url': null,
    'linkedin_url': null,
    'twitter_url': null,
    'portfolio_url': null,
    'location': 'Chattogram, Bangladesh',
    'timezone': 'Asia/Dhaka',
    'date_of_birth': null,
    'skill_level': 'beginner',
    'programming_languages': <String>['JavaScript'],
    'interests': <String>['Frontend Development'],
    'badges': <String>[],
    'daily_goal_minutes': 45,
    'email_notifications': true,
    'is_public': true,
    'current_streak': 3,
    'longest_streak': 7,
    'created_at': now.subtract(const Duration(days: 40)).toIso8601String(),
    'updated_at': now.toIso8601String(),
    'email_verified_at': now.toIso8601String(),
  };

  store.users
    ..add(admin)
    ..add(testUser);

  final seededBlogs = <Map<String, dynamic>>[
    <String, dynamic>{
      'title': 'Introduction to Laravel',
      'title_bn': 'লারাভেল পরিচিতি',
      'excerpt':
          'Learn the basics of Laravel framework and modern PHP development.',
      'excerpt_bn': 'লারাভেল ফ্রেমওয়ার্কের মূল বিষয়গুলি শিখুন।',
      'content':
          'Laravel is a web framework with elegant syntax and developer-friendly tooling.',
      'content_bn': 'লারাভেল একটি শক্তিশালী এবং মার্জিত ওয়েব ফ্রেমওয়ার্ক।',
      'author': 'John Doe',
      'author_bn': 'জন ডো',
      'author_id': admin['id'],
      'category': 'Web Development',
      'category_bn': 'ওয়েব ডেভেলপমেন্ট',
      'tags': <String>['Laravel', 'PHP', 'Framework'],
      'tags_bn': <String>['লারাভেল', 'পিএইচপি', 'ফ্রেমওয়ার্ক'],
      'read_time': '8 min read',
      'read_time_bn': '৮ মিনিট পড়ুন',
      'image_url': 'https://picsum.photos/800/400?random=1',
      'featured_image': null,
      'slug': 'introduction-to-laravel',
      'status': 'published',
      'views': 1234,
      'published_at': now.subtract(const Duration(days: 5)).toIso8601String(),
    },
    <String, dynamic>{
      'title': 'Getting Started with React',
      'title_bn': 'রিঅ্যাক্ট দিয়ে শুরু করা',
      'excerpt':
          'A practical guide to React fundamentals and component-driven UI.',
      'excerpt_bn': 'রিঅ্যাক্টের মৌলিক বিষয়ের একটি প্র্যাকটিক্যাল গাইড।',
      'content': 'React is a JavaScript library for building user interfaces.',
      'content_bn': 'রিঅ্যাক্ট একটি জনপ্রিয় জাভাস্ক্রিপ্ট লাইব্রেরি।',
      'author': 'Jane Smith',
      'author_bn': 'জেন স্মিথ',
      'author_id': admin['id'],
      'category': 'Frontend Development',
      'category_bn': 'ফ্রন্টএন্ড ডেভেলপমেন্ট',
      'tags': <String>['React', 'JavaScript', 'Frontend'],
      'tags_bn': <String>['রিঅ্যাক্ট', 'জাভাস্ক্রিপ্ট', 'ফ্রন্টএন্ড'],
      'read_time': '10 min read',
      'read_time_bn': '১০ মিনিট পড়ুন',
      'image_url': 'https://picsum.photos/800/400?random=2',
      'featured_image': null,
      'slug': 'getting-started-with-react',
      'status': 'published',
      'views': 2156,
      'published_at': now.subtract(const Duration(days: 3)).toIso8601String(),
    },
    <String, dynamic>{
      'title': 'Database Design Best Practices',
      'title_bn': 'ডাটাবেস ডিজাইনের সেরা অনুশীলন',
      'excerpt': 'Essential principles for scalable database schema design.',
      'excerpt_bn': 'স্কেলেবল ডাটাবেস স্কিমা ডিজাইনের গুরুত্বপূর্ণ নীতিগুলি।',
      'content':
          'This guide covers normalization, indexing, and relationship modeling.',
      'content_bn':
          'এই গাইডে নরমালাইজেশন, ইনডেক্সিং এবং সম্পর্ক নিয়ে আলোচনা করা হয়েছে।',
      'author': 'Mike Johnson',
      'author_bn': 'মাইক জনসন',
      'author_id': admin['id'],
      'category': 'Database',
      'category_bn': 'ডাটাবেস',
      'tags': <String>['Database', 'SQL', 'Design'],
      'tags_bn': <String>['ডাটাবেস', 'এসকিউএল', 'ডিজাইন'],
      'read_time': '12 min read',
      'read_time_bn': '১২ মিনিট পড়ুন',
      'image_url': 'https://picsum.photos/800/400?random=3',
      'featured_image': null,
      'slug': 'database-design-best-practices',
      'status': 'published',
      'views': 987,
      'published_at': now.subtract(const Duration(days: 7)).toIso8601String(),
    },
    <String, dynamic>{
      'title': 'Draft: Future of Web Development',
      'title_bn': 'খসড়া: ওয়েব ডেভেলপমেন্টের ভবিষ্যৎ',
      'excerpt': 'Exploring upcoming trends and technologies.',
      'excerpt_bn': 'ভবিষ্যতের প্রযুক্তিগত ট্রেন্ড নিয়ে আলোচনা।',
      'content': 'This is a draft article about the future of web development.',
      'content_bn': 'এটি ওয়েব ডেভেলপমেন্টের ভবিষ্যৎ নিয়ে একটি খসড়া নিবন্ধ।',
      'author': 'Alex Turner',
      'author_bn': 'অ্যালেক্স টার্নার',
      'author_id': admin['id'],
      'category': 'Web Development',
      'category_bn': 'ওয়েব ডেভেলপমেন্ট',
      'tags': <String>['Future', 'Trends', 'Web'],
      'tags_bn': <String>['ভবিষ্যৎ', 'ট্রেন্ড', 'ওয়েব'],
      'read_time': '5 min read',
      'read_time_bn': '৫ মিনিট পড়ুন',
      'image_url': 'https://picsum.photos/800/400?random=4',
      'featured_image': null,
      'slug': 'future-of-web-development',
      'status': 'draft',
      'views': 0,
      'published_at': null,
    },
  ];

  for (final data in seededBlogs) {
    store.blogs.add(<String, dynamic>{
      'id': store._blogId++,
      ...data,
      'created_at': now.subtract(const Duration(days: 9)).toIso8601String(),
      'updated_at': now.toIso8601String(),
    });
  }

  final seededExercises = <Map<String, dynamic>>[
    <String, dynamic>{
      'slug': 'build-a-simple-calculator',
      'title': 'Build a Simple Calculator',
      'title_bn': 'একটি সাধারণ ক্যালকুলেটর তৈরি করুন',
      'description': 'Create a calculator with arithmetic operations.',
      'description_bn': 'গণনার মৌলিক অপারেশনসহ একটি ক্যালকুলেটর তৈরি করুন।',
      'instructions':
          'Implement add, subtract, multiply, and divide functions.',
      'instructions_bn': 'যোগ, বিয়োগ, গুণ ও ভাগ ফাংশন তৈরি করুন।',
      'problem_statement': 'Write functions for basic arithmetic operations.',
      'problem_statement_bn': 'মৌলিক গাণিতিক অপারেশনের জন্য ফাংশন লিখুন।',
      'input_description': 'Two numbers a and b',
      'input_description_bn': 'দুটি সংখ্যা a এবং b',
      'output_description': 'Result of operation',
      'output_description_bn': 'অপারেশনের ফলাফল',
      'sample_input': 'a=5, b=2',
      'sample_input_bn': 'a=৫, b=২',
      'sample_output': 'add=7, sub=3, mul=10, div=2.5',
      'sample_output_bn': 'যোগ=৭, বিয়োগ=৩, গুণ=১০, ভাগ=২.৫',
      'difficulty': 'Beginner',
      'difficulty_bn': 'সহজ',
      'duration': 30,
      'duration_bn': '৩০ মিনিট',
      'category': 'Programming Basics',
      'category_bn': 'প্রোগ্রামিং বেসিক',
      'tags': <String>['JavaScript', 'Beginner', 'Functions'],
      'tags_bn': <String>['জাভাস্ক্রিপ্ট', 'শিক্ষানবিস', 'ফাংশন'],
      'starter_code': 'function add(a, b) {\n  // TODO\n}',
      'solution_code': 'function add(a, b) { return a + b; }',
      'programming_language': 'JavaScript',
      'language_id': 'javascript',
      'language_name': 'JavaScript',
      'language_name_bn': 'জাভাস্ক্রিপ্ট',
      'image_url': 'https://picsum.photos/800/400?random=101',
      'status': 'published',
      'views': 1456,
      'completions': 823,
      'published_at': now.subtract(const Duration(days: 10)).toIso8601String(),
    },
    <String, dynamic>{
      'slug': 'implement-binary-search-algorithm',
      'title': 'Implement a Binary Search Algorithm',
      'title_bn': 'একটি বাইনারি সার্চ অ্যালগরিদম বাস্তবায়ন করুন',
      'description': 'Write an efficient binary search in a sorted array.',
      'description_bn': 'সাজানো অ্যারেতে বাইনারি সার্চ লিখুন।',
      'instructions':
          'Use iterative or recursive approach and return index or -1.',
      'instructions_bn': 'পুনরাবৃত্তি বা লুপ ব্যবহার করে সূচক ফেরত দিন।',
      'problem_statement': 'Find target in sorted list with O(log n).',
      'problem_statement_bn': 'সাজানো তালিকায় O(log n) সময়ে target খুঁজুন।',
      'input_description': 'Sorted integer list and target',
      'input_description_bn': 'সাজানো পূর্ণসংখ্যার তালিকা এবং target',
      'output_description': 'Index of target or -1',
      'output_description_bn': 'target এর সূচক অথবা -১',
      'sample_input': 'arr=[1,3,6,9], target=6',
      'sample_input_bn': 'arr=[১,৩,৬,৯], target=৬',
      'sample_output': '2',
      'sample_output_bn': '২',
      'difficulty': 'Intermediate',
      'difficulty_bn': 'মাঝারি',
      'duration': 45,
      'duration_bn': '৪৫ মিনিট',
      'category': 'Algorithms',
      'category_bn': 'অ্যালগরিদম',
      'tags': <String>['Python', 'Algorithms', 'Search'],
      'tags_bn': <String>['পাইথন', 'অ্যালগরিদম', 'সার্চ'],
      'starter_code': 'def binary_search(arr, target):\n  pass',
      'solution_code':
          'def binary_search(arr, target):\n  # solved\n  return -1',
      'programming_language': 'Python',
      'language_id': 'python',
      'language_name': 'Python',
      'language_name_bn': 'পাইথন',
      'image_url': 'https://picsum.photos/800/400?random=102',
      'status': 'published',
      'views': 2341,
      'completions': 1234,
      'published_at': now.subtract(const Duration(days: 8)).toIso8601String(),
    },
    <String, dynamic>{
      'slug': 'build-rest-api-endpoint',
      'title': 'Build a REST API Endpoint',
      'title_bn': 'একটি REST API এন্ডপয়েন্ট তৈরি করুন',
      'description': 'Create a registration endpoint with validation.',
      'description_bn': 'ভ্যালিডেশনসহ রেজিস্ট্রেশন এন্ডপয়েন্ট তৈরি করুন।',
      'instructions': 'Validate input and return proper status codes.',
      'instructions_bn': 'ইনপুট যাচাই করে সঠিক স্ট্যাটাস কোড ফেরত দিন।',
      'problem_statement': 'Build secure user registration endpoint.',
      'problem_statement_bn':
          'নিরাপদ ব্যবহারকারী রেজিস্ট্রেশন এন্ডপয়েন্ট তৈরি করুন।',
      'input_description': 'name, email, password',
      'input_description_bn': 'name, email, password',
      'output_description': 'Success response or validation errors',
      'output_description_bn': 'সফল রেসপন্স বা ভ্যালিডেশন ত্রুটি',
      'sample_input': '{"name":"A","email":"a@x.com","password":"12345678"}',
      'sample_input_bn': '{"name":"A","email":"a@x.com","password":"12345678"}',
      'sample_output': '{"message":"created"}',
      'sample_output_bn': '{"message":"created"}',
      'difficulty': 'Advanced',
      'difficulty_bn': 'কঠিন',
      'duration': 90,
      'duration_bn': '৯০ মিনিট',
      'category': 'Backend Development',
      'category_bn': 'ব্যাকএন্ড ডেভেলপমেন্ট',
      'tags': <String>['Node.js', 'REST API', 'Validation'],
      'tags_bn': <String>['নোড.জেএস', 'REST API', 'ভ্যালিডেশন'],
      'starter_code': 'app.post("/api/register", (req,res) => {});',
      'solution_code': '// secure endpoint implementation',
      'programming_language': 'JavaScript',
      'language_id': 'javascript',
      'language_name': 'JavaScript',
      'language_name_bn': 'জাভাস্ক্রিপ্ট',
      'image_url': 'https://picsum.photos/800/400?random=105',
      'status': 'published',
      'views': 2987,
      'completions': 1456,
      'published_at': now.subtract(const Duration(days: 3)).toIso8601String(),
    },
  ];

  for (final data in seededExercises) {
    store.exercises.add(<String, dynamic>{
      'id': store._exerciseId++,
      ...data,
      'created_at': now.subtract(const Duration(days: 12)).toIso8601String(),
      'updated_at': now.toIso8601String(),
    });
  }

  final seededTutorials = <Map<String, dynamic>>[
    <String, dynamic>{
      'language_id': 'javascript',
      'title': 'Introduction to JavaScript',
      'content':
          'JavaScript is a lightweight interpreted language for modern web applications.',
      'code_example': 'console.log("Hello, World!");',
      'order': 1,
      'is_published': true,
    },
    <String, dynamic>{
      'language_id': 'javascript',
      'title': 'Variables and Data Types',
      'content': 'Use let and const for modern variable declarations.',
      'code_example': 'const age = 25;\nlet name = "Alice";',
      'order': 2,
      'is_published': true,
    },
    <String, dynamic>{
      'language_id': 'python',
      'title': 'Getting Started with Python',
      'content': 'Python focuses on readability and simplicity.',
      'code_example': 'print("Hello, World!")',
      'order': 1,
      'is_published': true,
    },
    <String, dynamic>{
      'language_id': 'html',
      'title': 'HTML Basics',
      'content': 'HTML structures your content for the web.',
      'code_example': '<h1>Hello World</h1>',
      'order': 1,
      'is_published': true,
    },
    <String, dynamic>{
      'language_id': 'react',
      'title': 'Introduction to React',
      'content': 'React helps build component-driven user interfaces.',
      'code_example': 'function App(){ return <h1>Hello</h1> }',
      'order': 1,
      'is_published': true,
    },
  ];

  for (final data in seededTutorials) {
    store.tutorials.add(<String, dynamic>{
      'id': store._tutorialId++,
      ...data,
      'created_at': now.subtract(const Duration(days: 15)).toIso8601String(),
      'updated_at': now.toIso8601String(),
    });
  }

  store.activities.add(<String, dynamic>{
    'id': store._activityId++,
    'user_id': testUser['id'],
    'minutes_active': 90,
    'lessons_completed': 2,
    'exercises_completed': 1,
    'quizzes_completed': 1,
    'blogs_read': 2,
    'comments_posted': 0,
    'code_snippets_created': 1,
    'created_at': now.subtract(const Duration(days: 1)).toIso8601String(),
    'updated_at': now.subtract(const Duration(days: 1)).toIso8601String(),
  });

  store.favorites.add(<String, dynamic>{
    'id': store._favoriteId++,
    'user_id': testUser['id'],
    'type': 'tutorial',
    'title': 'Introduction to JavaScript',
    'description': 'Great start for newcomers',
    'url': '/tutorials/1',
    'category': 'javascript',
    'tags': <String>['intro'],
    'order': 0,
    'created_at': now.subtract(const Duration(days: 2)).toIso8601String(),
    'updated_at': now.subtract(const Duration(days: 2)).toIso8601String(),
  });
}
